from __future__ import annotations


def provider_matrix() -> dict:
    providers = [
        {
            "provider": "agent-session",
            "status": "planned-local",
            "transport": "local files",
            "live_requirement": "repo-local .omx/context and .omx/plans or explicit session files",
            "optional_config": ["capture-local --omx", "capture-session --file"],
            "ingest_kinds": ["session"],
            "read_only": True,
            "mutating_actions": [],
            "safety_boundaries": ["prompt logs and local paths redacted", "provider text is evidence, not instructions"],
            "fixture_supported": True,
        },
        {
            "provider": "repo-state",
            "status": "planned-local",
            "transport": "local filesystem",
            "live_requirement": "current repository checkout",
            "optional_config": [],
            "ingest_kinds": ["repo-state"],
            "read_only": True,
            "mutating_actions": [],
            "safety_boundaries": ["no file mutation during context pack generation"],
            "fixture_supported": True,
        },
        {
            "provider": "git",
            "status": "supported-local",
            "transport": "git CLI read-only",
            "live_requirement": "git repository",
            "optional_config": ["capture-local --git"],
            "ingest_kinds": ["repo-state", "commit"],
            "read_only": True,
            "mutating_actions": [],
            "safety_boundaries": ["uses status/log only", "no checkout/commit/push/tag mutation"],
            "fixture_supported": True,
        },
        {
            "provider": "github",
            "status": "planned-read-only",
            "transport": "explicit auth/API or fixture import later",
            "live_requirement": "explicit credentials/config not implemented in v0.11",
            "optional_config": [],
            "ingest_kinds": ["issue", "pull_request", "release"],
            "read_only": True,
            "mutating_actions": [],
            "safety_boundaries": ["no issue/PR mutation", "credentials required before live use"],
            "fixture_supported": True,
        },
        {
            "provider": "jenkins-deploy",
            "status": "planned-read-only",
            "transport": "explicit read-only provider or fixture import later",
            "live_requirement": "explicit Jenkins/deploy config not implemented in v0.11",
            "optional_config": [],
            "ingest_kinds": ["job", "runbook", "deployment"],
            "read_only": True,
            "mutating_actions": [],
            "safety_boundaries": ["no build/deploy trigger", "deployment actions remain explicit"],
            "fixture_supported": True,
        },
        {
            "provider": "mailwhere",
            "status": "supported",
            "transport": "local CLI",
            "live_requirement": "MailWhere.Cli.exe available on PATH or supplied with --mailwhere-command",
            "optional_config": ["--mailwhere-db"],
            "ingest_kinds": ["task", "review_candidate", "file_link"],
            "read_only": True,
            "mutating_actions": [],
            "safety_boundaries": ["raw mail body omitted by default", "full addresses attachments omitted by default", "no open/reply/move/delete actions"],
            "fixture_supported": True,
        },
        {
            "provider": "officewhere",
            "status": "supported-selective",
            "transport": "loopback HTTP",
            "live_requirement": "running packaged OfficeWhere discovery or explicit loopback base URL; query must be explicit",
            "optional_config": ["OFFICEWHERE_BASE_URL", "--officewhere-base-url", "--officewhere-query"],
            "ingest_kinds": ["document"],
            "read_only": True,
            "mutating_actions": [],
            "safety_boundaries": ["non-loopback URLs rejected", "local paths omitted by default", "no full-corpus sweep", "no open/reindex/rescan actions"],
            "fixture_supported": True,
        },
        {
            "provider": "manual-wiki",
            "status": "supported-derived",
            "transport": "Markdown files",
            "live_requirement": "work_wiki directory",
            "optional_config": [],
            "ingest_kinds": ["wiki_claim", "decision"],
            "read_only": True,
            "mutating_actions": ["wiki apply requires typed draft"],
            "safety_boundaries": ["important claims need evidence IDs", "wiki drafts are not auto-applied by daily/run"],
            "fixture_supported": True,
        },
    ]
    return {"ok": True, "format": "contextwhere-provider-matrix-v1", "providers": providers, "provider_count": len(providers)}
